/*
--여러행 (그룹) 함수 
AVG() -평균
MIN() - 최소값
MAX() - 최대값
SUM()- 합계 
*/
SELECT AVG(SALARY) AS AVG_SALARY, 
    MAX(SALARY) AS MAX_SALARY, 
    MIN(SALARY) AS MIN_SALARY, 
    SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
WHERE JOB_ID LIKE '%REP%';

--앞뒤에 상관없이 rep의 직급이 포함된 직원들의 salary 표기 


--COUNT () 함수 - null값이 아닌 모든 행의 개수를 반환합니다. 
SELECT COUNT (*) AS TOTAL_EMPLOYEES
FROM EMPLOYEES
WHERE DEPARTMENT_ID= 50;
--(*)자리에 COLUMN name을 넣으면 됨 

SELECT COUNT (COMMISSION_PCT) AS NON_NULL_COMMISSION_COUNT
FROM EMPLOYEES
WHERE DEPARTMENT_ID= 50;

SELECT COUNT (COMMISSION_PCT) AS NON_NULL_COMMISSION_COUNT
FROM EMPLOYEES
WHERE DEPARTMENT_ID= 80;

SELECT COUNT (NVL(COMMISSION_PCT,0)) AS NON_NULL_COMMISSION_COUNT
FROM EMPLOYEES
WHERE DEPARTMENT_ID= 50;

--departemnt id 45개가 나옴 -> (*)도 45개 -> count(1) 어차피 1로 뜰 행의 갯수를 나타내는 것이기에 45로 동일하다. 
--NULL은 카운트가 되지 않음 